diploma/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('order/', include('order.urls')),
    ]

order/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path

from order import views

app_name = 'order'
urlpatterns = [
                  url(r'^create/$', views.order_create_view, name='order_create'),
                  path('success', views.order_created_view, name='order_created')
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path, include
from . import views

urlpatterns = [
                  url('order/', include('order.urls', namespace='order')),
                  path('', views.base_view, name='main_page'),
                  path('<str:category_name>/<slug:slug>/', views.object_view, name='object_view'),
                  path('<slug:slug>', views.category_view, name='category_view'),
                  path('login/', views.login_view, name='login'),
                  path('logout/', views.logout_view, name='logout'),
                  path('registration/', views.registration_view, name='registration'),
                  path('cart/', views.cart_view, name='cart'),
                  path('add/<int:product_id>', views.cart_add, name='cart_add'),
                  path('delete_item/<int:product_id>', views.delete_item, name='cart_delete_item'),
                  path('delete/<int:product_id>', views.cart_remove, name='cart_delete_product'),
                  path('clear/', views.cart_clear, name='cart_clear'),
                  path('order_failed/', views.order_failed, name='order_failed'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from datetime import datetime

from django.db import models


class Product(models.Model):
    '''
        Модель для товара
    '''
    name = models.CharField(verbose_name='Название', max_length=25)
    category = models.ForeignKey("Category", on_delete=models.CASCADE, related_name='products')
    description = models.TextField(verbose_name='Описание')
    price = models.DecimalField(verbose_name='Стоимость', max_digits=8, decimal_places=2, null=True)
    image = models.ImageField(verbose_name='Изображение')
    slug = models.SlugField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"


class Category(models.Model):
    '''
    Модель для категории товара
    '''
    name = models.CharField("Название категории", max_length=150)
    description = models.TextField(verbose_name='Описание', blank=True)
    slug = models.SlugField()

    def __str__(self):
        return self.name



    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Review(models.Model):
    '''Модель для отзывов'''
    text = models.TextField(verbose_name="Текст отзыва", max_length=500)
    item = models.ForeignKey("Product", on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(verbose_name="Имя", max_length=50)
    rating = models.IntegerField(verbose_name="Рейтинг", null=True, blank=True)
    timestamp = models.DateTimeField(verbose_name="Метка времени",default=datetime.now())
    session = models.CharField(verbose_name="Идентиифкатор сессии",max_length=200, null=True, blank=True)

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

shop/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class ReviewForm(forms.Form):
    CHOICES = [('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ]
    name = forms.CharField(label='Имя', required=True,
                           max_length=150,
                           widget=forms.TextInput(attrs={'placeholder': 'Введите имя',
                                                         'class': 'form-control'
                                                         })
                           )
    text = forms.CharField(label='Текст',
                           required=False,
                           widget=forms.Textarea({'placeholder': 'Текст отзыва',
                                                  'class': 'form-control'
                                                  })
                           )
    stars = forms.ChoiceField(label='Оценка',
                              required=True,
                              widget=forms.RadioSelect(choices=CHOICES, ),
                              choices=CHOICES, )


class RegistrationForm(UserCreationForm):
    username = forms.CharField(required=True,
                               max_length=30,
                               widget=forms.TextInput(attrs={'placeholder': 'Логин',
                                                             'class': 'form-control'
                                                             }))
    email = forms.CharField(required=True,
                            max_length=150,
                            widget=forms.TextInput(attrs={'placeholder': 'E-mail',
                                                          'class': 'form-control'
                                                          }))

    password1 = forms.CharField(min_length=8, max_length=30,
                                widget=forms.PasswordInput(
                                    attrs={'placeholder': 'Пароль',
                                           'class': 'form-control'
                                           }),
                                required=True)
    password2 = forms.CharField(min_length=8, max_length=30,
                                required=True,
                                widget=forms.PasswordInput(
                                    attrs={'placeholder': 'Повторите пароль',
                                           'class': 'form-control'
                                           }))

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError(message="Пароли не совпадают!")
        return cd['password2']


class LoginForm(forms.Form):
    username = forms.CharField(label='Логин',
                               max_length=50,
                               widget=forms.TextInput
                               )
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput)


class CartAddForm(forms.Form):
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

# class CartRemoveForm(forms.Form):
#

shop/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from shop.cart import Cart
from .forms import ReviewForm, RegistrationForm, LoginForm, CartAddForm
from .models import Product, Review, Category


def get_session_id(request):
    if not request.user.is_authenticated:
        user_session = request.session.session_key
        if not user_session:
            user_session = request.session.cycle_key()
    else:
        user_session = request.user.username
    return user_session


def base_view(request):
    template = "shop/main.html"
    products = Product.objects.all()
    categories = Category.objects.all()
    cart = Cart(request)
    cart_len = len(cart)
    context = {'products': products,
               'categories': categories,
               'cart_len': cart_len, }

    return render(request, template, context)


def category_view(request, slug):
    template = "shop/category.html"
    category = Category.objects.get(slug=slug)
    categories = Category.objects.all()
    category_slug = slug
    products = category.products.all()
    cart = Cart(request)
    current_page = request.GET.get('page', 1)
    paginator = Paginator(products, 3)
    page_items = paginator.get_page(current_page)
    prev_page_url = None
    next_page_url = None
    if page_items.has_next():
        next_page_url = page_items.next_page_number()
    if page_items.has_previous():
        prev_page_url = page_items.previous_page_number()
    context = {
        'category': category,
        'categories': categories,
        'category_slug': category_slug,
        'cart_len': len(cart),
        'products': products,
        'page': current_page,
        'page_items': page_items,
        'prev_page_url': prev_page_url,
        'next_page_url': next_page_url,
    }
    return render(request, template, context)


def object_view(request, category_name, slug):
    user_session = request.session.session_key
    template = "shop/shop_item.html"
    product = get_object_or_404(Product, slug=slug)
    form = ReviewForm()
    identifier = product.id
    reviews = Review.objects.filter(item=product.id).order_by('-timestamp')
    categories = Category.objects.all()
    cart_product_form = CartAddForm()
    cart = Cart(request)
    context = {
        'item': product,
        'reviews': reviews,
        'identifier': identifier,
        'form': form,
        'categories': categories,
        'cat_name': category_name,
        'slug': slug,
        'cart_product_form': cart_product_form,
        'cart_len': len(cart)
    }
    for review in reviews:
        if review.session == user_session:
            context["reviewed"] = True
            break
    if not user_session:
        request.session.cycle_key()
        user_session = request.session.session_key
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            Review.objects.create(item=Product.objects.get(id=identifier),
                                  name=form.cleaned_data.get('name'),
                                  text=form.cleaned_data.get('text'),
                                  rating=form.cleaned_data.get('stars'),
                                  session=user_session
                                  )
            return redirect('object_view', category_name=category_name, slug=slug)
    return render(request, template, context)


def cart_clear(request):
    cart = Cart(request)
    form = CartAddForm(request.POST)
    if form.is_valid():
        cart.clear()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    form = CartAddForm(request.POST)
    product = (get_object_or_404(Product, id=product_id))
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=1,
                 update_quantity=cd['update'])
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@require_POST
def delete_item(request, product_id):
    cart = Cart(request)
    form = CartAddForm(request.POST)
    product = (get_object_or_404(Product, id=product_id))
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=-1,
                 update_quantity=cd['update'])
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    form = CartAddForm(request.POST)
    product = get_object_or_404(Product, id=product_id)
    if form.is_valid():
        cart.remove(product=product)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def cart_view(request):
    template = "shop/cart.html"
    cart = Cart(request).__repr__()
    categories = Category.objects.all
    products_in_cart = dict()
    products = Product.objects.all()
    for obj in products:
        if str(obj.id) in cart:
            products_in_cart[obj.id] = {'name': obj.name,
                                        'description': obj.description,
                                        'quantity': cart[str(obj.id)]['quantity']}
    context = {'cart': cart,
               'products_in_cart': products_in_cart,
               'cart_len': len(Cart(request)),
               'products': products,
               'categories':categories}

    return render(request, template, context)


def registration_view(request):
    template = "shop/registration.html"
    reg_form = RegistrationForm()
    context = {'user_form': reg_form}
    if request.method == 'POST':
        reg_form = RegistrationForm(request.POST)
        if reg_form.is_valid():
            new_user = reg_form.save(commit=False)
            new_user.set_password(reg_form.cleaned_data['password2'])
            new_user.save(messages.success(request, ''))
            return render(request, "shop/registration_done.html")
        else:
            messages.error(request, message="Пароли не совпадают!")
    return render(request, template, context)


def login_view(request):
    login_form = LoginForm()
    context = {'login_form': login_form}
    template = "shop/login.html"
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main_page')
        else:
            messages.info(request, 'Неверные логин или пароль!')
    return render(request, template, context)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def order_failed(request):
    template = "shop/empty_section.html"
    categories = Category.objects.all()
    return render(request, template, {'categories': categories,
                                      'cart_len': len(Cart(request))})

shop/templates/shop/base.html
<!DOCTYPE html>
<!--{%load staticfiles%}-->
{%load static%}
<html lang="en" >
<head>
<!--  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">-->
<!--  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">-->
  <title>Graduation Work</title>
    <link rel="stylesheet" href="{% static '/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/main.css' %}">
    <link rel="stylesheet" href="{% static '/styles.css' %}">



</head>
<body class="" data-gr-c-s-loaded="true">


{%include "shop/navigation.html"%}
{%block content%}

{%endblock%}

<script src="{% static '/bootstrap.min.js' %}"></script>
<script src="{% static '/jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static '/popper.min.js' %}"></script>
</body>
</html>

shop/templates/shop/cart.html
{% extends '../shop/base.html' %}
{%load static %}
{% load i18n %}
{% load filters %}
{%block content%}
<div class="container mt-3">
  <div class="row">
    <div class="col-lg-6 col-md-9 col-sm-12 order-md-2 mb-4">
      {%if cart_len < 1%}
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Ваша корзина пуста</span>
      </h4>
      {%else%}
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Ваша корзина</span>
        <span class="badge badge-secondary badge-pill">{{cart_len}}</span>
      </h4>
      <ul class="list-group mb-3">
        {%for key, values_list in products_in_cart.items%}

        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div style="display:inline">
            <h6 class="my-0">{{values_list.name}}</h6>
            <small class="text-muted">{{values_list.description}}</small>
            </div>
          <div style="display:inline-block; float:right; margin-right:.rem;">
            <div style="display:inline-block; float:left">
              {% if values_list.quantity > 1 %}

                <form style="float: left;" action="{% url 'cart_delete_item' product_id=key %}" method="post" >
                  {% csrf_token %}
                  {{form}}
                  <button type="submit" class="btn1 btn-secondary">-</button>
                </form>
              {% else %}
                <form style="float: left;" action="." method="post" >
                  {% csrf_token %}
                  {{form}}
                  <button disabled="disabled" type="submit" class="btn1 btn-secondary">-</button>
                </form>
              {% endif %}

                <span class="text_cart">{{values_list.quantity}} </span>

              <form style="float: right;" action="{% url 'cart_add' product_id=key %}" method="post" >
                {% csrf_token %}
                {{form}}
                <button type="submit" class="btn1 btn-secondary">+</button>
              </form>
          </div>
            <form style="float: right;" action="{% url 'cart_delete_product' product_id=key %}" method="post" >
                {% csrf_token %}
                {{form}}
                <button type="submit" style="color:white; border:none; background-color:white;">
                  <img src="{% static 'dustbin.svg' %}" style="margin-left:.5rem" width="25" height="25">
                </button>
              </form>
          </div>

        </li>
        {%endfor%}
      </ul>
      <div style="display:inline-block">
        {% if user.is_authenticated %}
          <form style="display:inline-block" action="{% url 'order:order_create' %}" method="post" >
            {% csrf_token %}
            {{form}}
            <button type="submit" class="btn btn-secondary">Заказать</button>
          </form>
        {%else%}
        <a href = "{% url 'order_failed' %}"><button type="submit" class="btn btn-secondary">Заказать</button></a>
        {% endif %}
        <form style="display:inline-block" action="{% url 'cart_clear' %}" method="post" >
           {% csrf_token %}
           {{form}}
           <button type="submit" class="btn btn-secondary">Очистить корзину</button>
         </form>
           {% csrf_token %}


      </div>
      {%endif%}

    </div>
  </div>
</div>
{%endblock content%}

shop/templates/shop/category.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
<main role="main">
<br><br>
<div class="container">
    <div class="">
              {% if not page_items  %}
                  <h2>Здесь пока ничего нет</h2>
              {% else %}

                  <h2 align="center" style="background-color:;">{{category}}</h2>
        <div class="row" style="padding-top:2rem;">
              {% for product in page_items %}

                  <div style="display:block; align:center;" >
                    <h4 align="center">{{ product.name }}</h4>
                    <a href=./{{ category_slug }}/{{ product.slug }} >
                      <img src={{ product.image.url }} style="width: auto; height: 25rem;
                      overflow: hidden; display: inline; justify-content: center; align-items: center; margin-bottom:1.25rem;"
                           width="auto" height="100%">
                      </a>
                    <form method="post" align ="center" action="{% url 'cart_add' product_id=product.id %}">
                        {% csrf_token %}
                        {{cart_product_form}}
                      <input type="submit" class="btn btn-secondary" align="center" value="Добавить в корзину »">
                    </form>
                  </div>
                {% endfor %}
              {% endif %}
    </div>
    <div class="row">
        <div class="col-md-12" style="margin-top: 20px;">
            {% if page_items.has_previous %}
                <a href="?page={{ prev_page_url }}">Предыдущая</a>
                {% endif %}
            {% if page_items.has_next %}
                <a href="?page={{ next_page_url }}">Следующая</a>
                {% endif %}
        </div>
    </div>
</div>
</main>
{% endblock %}
<hr>
<footer class="container">
  <p>© Просто магазин 2018</p>
</footer>

shop/templates/shop/empty_section.html
{% extends "shop/base.html"%}
{%load static%}

{%block content%}
<main role="main">

  <div class="container">
    <!-- Example row of columns -->


    <div class="alert alert-dark" role="alert">
      Для оформления заказа нужно <a  href="{% url 'login' %}">авторизоваться</a> или
      <a href = "{% url 'registration' %}">зарегистрироваться</a> на сайте
    </div>


  </div> <!-- /container -->

</main>
{% endblock %}

shop/templates/shop/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Graduation Work</title>
  <link rel="stylesheet" href="{% static '/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '/main.css' %}">
  <link rel="stylesheet" href="{% static '/styles.css' %}">
  <link rel="stylesheet" href="{% static '/login.css' %}">
</head>
<body class="text-center" data-gr-c-s-loaded="true">


<form class="form-signin" action="." method="post">
  <input type="hidden" name="next" value="">
    {% csrf_token %}
  <img class="mb-4" src="../../static/logo.svg" alt="" width="72" height="72">

  <h1 class="h3 mb-3 font-weight-normal">Вход</h1>
  <label for="username" class="sr-only">Email</label>
  <input type="text" class="form-control" placeholder="Login" name="username"
         value="">
  <label for="password" class="sr-only">Password</label>
  <input type="password" class="form-control" placeholder="Пароль"
         name="password" >
    {% for message in messages %}
        {{ message }}
    {% endfor %}

  <p>Нет аккаунта?</p>
  <a href =/registration/ >Зарегистрироваться</a>
<br>
<br>
<br>
  <button class="btn btn-lg btn-primary btn-block" type="submit" value="login" >Войти</button>
  <p class="mt-5 mb-3 text-muted">© Просто магазин</p>
  <a href="{% url 'main_page'%}">На главную</a>

</form>

<script src="{% static '/bootstrap.min.js' %}"></script>
<script src="{% static '/jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static '/popper.min.js' %}"></script>
</body>
</html>

shop/templates/shop/main.html
{% extends '../shop/base.html' %}
{%load static%}
{%block content%}
<div role="main">

  <div class="jumbotron">
    <div class="container">
        <h1 class="display-4">Добро пожаловать на сайт просто магазина</h1>
    </div>
  </div>
        {%for category in categories%}
            <div class="jumbotron">
                <h2>{{category.name}}</h2>
                <P>{{ category.description}}</P>
            </div>
            <div class="container mb-5">
                  <div class="row" align="center">
                  {% if not products %}
                      <p>Здесь пока ничего нет</p>
                  {% else %}
                    {% for product in products %}
                      {% if  product.category_id == category.id%}
                      <div class="col-md-4" >
                        <h2 >{{ product.name }}</h2>
                        <a href=/{{ category.slug }}/{{ product.slug }} >
                          <img src={{ product.image.url }} style="width: auto; height: 15rem;
                          overflow: hidden; display: inline; justify-content: center; align-items:
                          center; padding-bottom:1.5rem;" height="100%" width="auto">
                          </a>
                        <form method="post"  align ="center" action="{% url 'cart_add' product_id=product.id %}">
                            {% csrf_token %}
                            {{cart_product_form}}
                            <input type="submit" class="btn btn-secondary" value="Добавить в корзину »">
                        </form>
                          </div>
                      {% endif %}
                    {% endfor %}
                  {% endif %}
              </div>
            </div>
    {% endfor %}

<hr>
<footer class="container">
  <p>© Просто магазин </p>
</footer>

{%endblock%}

shop/templates/shop/navigation.html
{% load static%}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" width ='95%'>
  <a class="navbar-brand" href="/">Просто магазин</a>
   <img src="{% static 'logo.svg' %}" width="42" height="42">
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">
          Главная</a>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01"
             data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Гаджеты</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
              {% for category in categories %}
                  <a class="dropdown-item" href="{% url 'category_view' category.slug %}">
                  {{ category }}
                  </a>
              {% endfor %}
          </div>

      </li>
    </ul>
        {% if user.is_authenticated  %}
        <p class="username">
            Привет, {{ user.username }}
        </p>
        <a class="btn btn-outline-success my-2 my-sm-0" role="button"
           href="{% url 'logout' %}">
            Выйти</a>

        {% else %}
        <a class="btn btn-outline-success my-2 my-sm-0" role="button"
           href="{% url 'login' %}">
            Войти</a>

        {% endif %}
        <a class="btn btn-outline-success my-2 my-sm-0" role="button"
           href="{% url 'cart' %}">
            Корзина
           <span class="quantity" >
           <div class="circle">{{cart_len}}</div>
           </span>
        </a>
  </div>
    <script src="{% static '/bootstrap.min.js' %}"></script>
<script src="{% static '/jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static '/popper.min.js' %}"></script>
</nav>

shop/templates/shop/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Graduation Work</title>
  <link rel="stylesheet" href="{% static '/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '/main.css' %}">
  <link rel="stylesheet" href="{% static '/styles.css' %}">
  <link rel="stylesheet" href="{% static '/login.css' %}">
</head>
<body class="text-center" data-gr-c-s-loaded="true">


<form class="form-signin" action="." method="post">
    {% csrf_token %}
  <input type="hidden" name="next" value="">
  <img class="mb-4" src="../../static/logo.svg" alt="" width="72" height="72">
    <p>Есть аккаунт? <a href = "{% url 'login' %}">Войти</a></p>
    <p>Введите данные:</p>
    {{ user_form.username }}
    <br>
    {{ user_form.email }}
    <br>
    {{ user_form.password1 }}
    <br>
    {{ user_form.password2 }}

  <button class="btn btn-lg btn-primary btn-block" type="submit">Зарегистрироваться</button>
    {% for message in messages %}
        {{ message }}
    {% endfor %}
  <p class="mt-5 mb-3 text-muted">© Просто магазин</p>
  <a href="{% url 'main_page' %}">На главную</a>
</form>
<script src="{% static '/bootstrap.min.js' %}"></script>
<script src="{% static '/jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static '/popper.min.js' %}"></script>
</body>
</html>

shop/templates/shop/registration_done.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Graduation Work</title>
    <link rel="stylesheet" href="{% static '/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/main.css' %}">
    <link rel="stylesheet" href="{% static '/styles.css' %}">
</head>

<body class="text-center" data-gr-c-s-loaded="true">
<div class="container">
    <h1 class="display-4">Добро пожаловать {{ new_user.first_name }}!</h1>
    <p>Аккаунт создан. Вы можете  <a href="{% url "login" %}">войти в систему</a>.</p>
</div>
</body>
<script src="{% static '/bootstrap.min.js' %}"></script>
<script src="{% static '/jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static '/popper.min.js' %}"></script>
</html>

shop/templates/shop/shop_item.html
{% extends 'shop/base.html' %}
{% load i18n %}
{% load filters %}
{% block content %}
{%load static%}
<div class="container mt-3">
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-4" align ="center">
            <h2>{{ item.name }}</h2>
            <img src={{ item.image.url }} style="width: auto; height: 25rem;
                      overflow: hidden; display: inline; margin-bottom:1.25rem;" width="auto" height="100%">
            <p>{{ item.price }} руб</p>
            <p>{{ item.description }}</p>
            <form method="post" action="{% url 'cart_add' product_id=identifier %}">
                {% csrf_token %}
                {{cart_product_form}}
                <input type="submit" class="btn btn-secondary" value="Добавить в корзину »">
            </form>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-12">
            {% if reviewed %}
            <h4>Вы уже оставляли отзыв</h4>

            {% else %}
            <h4>Оставьте отзыв:</h4>

            <form action="{% url 'object_view' category_name=cat_name slug=slug %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.name }}<br>{{ form.text }}<br>{{ form.stars }}
                </div>
                <button type="submit" class="btn btn-primary">Оставить</button>
            </form>
            {% endif %}
            <br>
            <h4>Отзывы:</h4>
            <hr>
            <div>
                {% for review in reviews %}
                    {% if review.item_id == identifier %}
                    <h4>{{ review.name }}</h4>
                    <p>{{ review.timestamp }}</p>
                    <p>{{ review.rating|stars_render }}</p>
                    <p> {{ review.text }}</p>
                    {% endif %}
                    <hr>
                {% endfor %}
                </span>
            </div>
        </div>
    </div>
</div>
{% endblock %}